data:
  dataset_name: tmp
  # seed data
  source_path: ../data/raw/dapo_math_15k_cot.json
  system: "Please reason step by step, and put your final answer within \\boxed{}."

target_dir: ../data/result
output_format: parquet # jsonl, json or parquet
get_test_set: False
test_ratio: 0.02 # The proportion of the test set

process:
  seed: 26
  tmp_folder: ../data/tmp

  template_and_code_generation:
    is_parallel: True
    system: ""
    sampling-params:
      temperature: 0
      top_p: 0.95
      max_tokens: 16384
      n: 1
      # extra_body="{"chat_template_kwargs": {"enable_thinking": False}},
    # For Local Serial
    generate_model_path: ""
    tensor_parallel_size: -1 # -1 means number of all available gpus
    gpu_memory_utilization: 0.95
    # For Remote Parallel
    url: ""
    api_key: "EMPTY"
    bsz: 1024

  controllable_perturbation:
    alpha_list: [5] # Optional values of the perturbation magnitude
    sample_times: 4 # The number of perturbations for each sample
    timeout_seconds_total: 180 # If a all perturbatio for more than the specified time, it is regarded as an error
    timeout_seconds_per_sample: 2 # If a one perturbation runs for more than the specified time, it is regarded as an error
    retry_times_inner: 10 # retry times for valid perturbation
    retry_times_outer: 50 # retry times for sanity check
    max_workers: -1 # -1 means the number of physical cores of the CPU
    chunk_size: 5

  sanity_check:
    is_parallel: True
    system: ""
    sampling-params:
      temperature: 1.0
      top_p: 0.95
      max_tokens: 32768
      n: 5
    # For Local Serial
    generate_model_path: ""
    tensor_parallel_size: -1 # -1 means number of all available gpus
    gpu_memory_utilization: 0.95
    # For Remote Parallel
    url: ""
    api_key: "EMPTY"
    bsz: 1024

  query_paraphrase:
    is_parallel: True
    system: ""
    sampling-params:
      temperature: 1.0
      top_p: 0.95
      max_tokens: 32768
      n: 5
    # For Local Serial
    generate_model_path: ""
    tensor_parallel_size: -1 # -1 means number of all available gpus
    gpu_memory_utilization: 0.95
    # For Remote Parallel
    url: ""
    api_key: "EMPTY"
    bsz: 1024



